[package]
name = "roommate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.69"
serde = {version = "1.0.130", features = ["derive"]}
tokio = { version = "1.4.0", features = ["full"] }
tokio-tungstenite = "0.14.0"
tungstenite = "0.13.0"
futures-util = "0.3.13"